AWSTemplateFormatVersion: '2010-09-09'
Description: Create resoureces in KeySpaces account
Parameters:
  VPCCidr:
    Default: 10.0.0.0/16
    Type: String
    Description: Cidr block of the VPC to be created
  PeerVPCCidr:
    Default: NONE
    Type: String
    Description: Cidr block of the VPC to be peered
  PeerAccountId:
    Type: String
    Description: The account id of the requester
    Default: NONE
  VPCStackTemplateUrl:
    Type: String
    Description: The S3 URL of the VPC stack template
  KeyspaceName:
    Default: "catalog"
    Type: String
    Description: Name of the Keyspace to be created

Conditions:
  CreatePeeringAcceptorRole: !Not [!Equals [!Ref PeerAccountId, 'NONE']]


Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VPCStackTemplateUrl
      Parameters:
        VPCName: "keyspaces-vpc"
        VPCCidr: !Ref VPCCidr
        PeerVPCCidr: !Ref PeerVPCCidr
        IfCreatePublicSubnet: "false"
        IfCreateS3Endpoint: "false"
        IfCreateSTSEndpoint: "false"
        IfCreateKeySpacesEndpoint: "true"
  MyNewKeyspace:
    Type: AWS::Cassandra::Keyspace
    Properties:
      KeyspaceName: !Ref KeyspaceName
      Tags:
        - Key: name
          Value: !Ref KeyspaceName
        - Key: stack
          Value: !Ref AWS::StackName
  KeySpacesEndPointPermissionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Allow access Keyspaces endpoint'
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
            - 'ec2:DescribeNetworkInterfaces'
            - 'ec2:DescribeVpcEndpoints'
          Resource: '*'
  KeySpacesAccountRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonKeyspacesFullAccess
        - !Ref KeySpacesEndPointPermissionPolicy
  vpcPeeringAcceptorRole:
    Type: 'AWS::IAM::Role'
    Condition: CreatePeeringAcceptorRole
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Principal:
              AWS: !Ref PeerAccountId
            Action:
              - 'sts:AssumeRole'
            Effect: Allow
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'ec2:AcceptVpcPeeringConnection'
                Resource: '*'
Outputs:
  keySpaceName:
    Description: The name of the Keyspace
    Value: !Ref MyNewKeyspace
    Export:
      Name: !Sub "${AWS::StackName}-MyNewKeyspace"
  keySpacesAccountRoleName:
    Description: The Name of the role in the keyspaces account
    Value: !Ref KeySpacesAccountRole
  keySpacesAccountRoleArn:
    Description: The ARN of the role in the keyspaces account
    Value: !GetAtt KeySpacesAccountRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-KeySpacesAccountRole"
  keyspacesVpcId:
    Description: The VPC id
    Value: !GetAtt VPC.Outputs.VPCId
  keyspacesActPrivateRouteTableId:
    Description: The private route table id
    Value: !GetAtt VPC.Outputs.PrivateRouteTableId
  keySpacesEndpointDns:
    Description: The Keyspaces endpoint DNS
    Value: !GetAtt VPC.Outputs.KeySpacesEndpointDns
  vpcPeeringAcceptorRoleArn:
    Description: The ARN of VPC peering acceptor role in the keyspaces account
    Value: !GetAtt vpcPeeringAcceptorRole.Arn
    Condition: CreatePeeringAcceptorRole
    Export:
      Name: !Sub "${AWS::StackName}-vpcPeeringAcceptorRole"
#  createPeeringConnectionCommand:
#    Description: The schema creation command
#    Value: !Sub "aws ec2 create-vpc-peering-connection --vpc-id SPARK_VPC_ID --peer-vpc-id ${VPC.Outputs.VPCId} --peer-owner-id ${AWS::AccountId}"
#  describePeeringConnectionCommand:
#    Description: The schema creation command
#    Value: !Sub "aws ec2 describe-vpc-peering-connections --filters Name=accepter-vpc-info.vpc-id,Values=${VPC.Outputs.VPCId}"
